server:
  port: ${PORT:8080}

spring:
  application:
    name: flowforge-backend

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/flowforge_db}
    username: ${SPRING_DATASOURCE_USERNAME:flowforge_user}
    password: ${SPRING_DATASOURCE_PASSWORD:1434@Sharath}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:mock@flowforge.com}
    password: ${MAIL_PASSWORD:mockpassword}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

app:
  jwt:
    secret: ${JWT_SECRET:flowforge-super-secret-key-minimum-256-bits-long-for-hs256}
    access-token-expiry: 86400000
    refresh-token-expiry: 604800000
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
